import { MCUItem } from './types';

export const SERIES_ROAD_ROWS: MCUItem[][] = [
  // Row 1 (L -> R)
  [
    {
      id: 's1',
      title: 'Daredevil',
      releaseDate: 'Apr 10, 2015',
      chronologicalOrder: 11,
      releaseOrder: 11,
      isEssential: false,
      summary: 'Matt Murdock fights crime in Hell’s Kitchen as a blind lawyer turned vigilante.',
      imdbRating: 8.6,
      mediaType: 'series',
      rowIndex: 0,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Establishes the gritty street-level Earth-616 dimension pre-Doomsday.',
      runtime: '3 Seasons',
      phase: 2,
    },
    {
      id: 's2',
      title: 'Jessica Jones',
      releaseDate: 'Nov 20, 2015',
      chronologicalOrder: 13,
      releaseOrder: 13,
      isEssential: false,
      summary: 'A super-powered private investigator faces her dark past and mind-controlling Kilgrave.',
      imdbRating: 7.9,
      mediaType: 'series',
      rowIndex: 0,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'Defines street-level heroes available for secret wars recruitment.',
      runtime: '3 Seasons',
      phase: 2,
    },
  ],
  // Row 2 (R -> L)
  [
    {
      id: 's4',
      title: 'Luke Cage',
      releaseDate: 'Sep 30, 2016',
      chronologicalOrder: 16,
      releaseOrder: 16,
      isEssential: false,
      summary: 'Bulletproof hero Luke Cage protects Harlem from corrupt mob bosses.',
      imdbRating: 7.3,
      mediaType: 'series',
      rowIndex: 1,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'Street-level hero anchor point.',
      runtime: '2 Seasons',
      phase: 3,
    },
    {
      id: 's3',
      title: 'Iron Fist',
      releaseDate: 'Mar 17, 2017',
      chronologicalOrder: 17,
      releaseOrder: 17,
      isEssential: false,
      summary: 'Danny Rand returns to NYC with the mystical power of the Iron Fist.',
      imdbRating: 6.4,
      mediaType: 'series',
      rowIndex: 1,
      posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&q=80',
      multiverseNote: 'Mystic chi energy connection to K’un-Lun.',
      runtime: '2 Seasons',
      phase: 3,
    },
  ],
  // Row 3 (L -> R)
  [
    {
      id: 's5',
      title: 'The Defenders',
      releaseDate: 'Aug 18, 2017',
      chronologicalOrder: 19,
      releaseOrder: 19,
      isEssential: false,
      summary: 'Daredevil, Jessica Jones, Luke Cage, and Iron Fist unite against the Hand.',
      imdbRating: 7.2,
      mediaType: 'series',
      rowIndex: 2,
      posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80',
      multiverseNote: 'First team-up of street-level vigilantes.',
      runtime: '1 Season',
      phase: 3,
    },
    {
      id: 's6',
      title: 'The Punisher',
      releaseDate: 'Nov 17, 2017',
      chronologicalOrder: 20,
      releaseOrder: 20,
      isEssential: false,
      summary: 'Frank Castle seeks revenge on those responsible for the death of his family.',
      imdbRating: 8.5,
      mediaType: 'series',
      rowIndex: 2,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Uncompromising tactical hero operating in NYC.',
      runtime: '2 Seasons',
      phase: 3,
    },
  ],
  // Row 4 (L -> R)
  [
    {
      id: 's7',
      title: 'WandaVision',
      releaseDate: 'Jan 15, 2021',
      chronologicalOrder: 27,
      releaseOrder: 27,
      isEssential: false,
      summary: 'Wanda Maximoff creates a sitcom hex world to cope with loss, unleashing reality manipulation.',
      imdbRating: 7.9,
      mediaType: 'series',
      rowIndex: 3,
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=80',
      multiverseNote: 'First reality distortion anomaly triggering the Scarlet Witch prophetical awakening.',
      runtime: '9 Episodes',
      phase: 4,
    },
    {
      id: 's8',
      title: 'The Falcon and the Winter Soldier',
      releaseDate: 'Mar 19, 2021',
      chronologicalOrder: 28,
      releaseOrder: 28,
      isEssential: false,
      summary: 'Sam Wilson and Bucky Barnes team up to stop the Flag Smashers and claim the shield.',
      imdbRating: 7.1,
      mediaType: 'series',
      rowIndex: 3,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'Sets up Sam Wilson as Captain America leading into Brave New World.',
      runtime: '6 Episodes',
      phase: 4,
    },
  ],
  // Row 5 (R -> L)
  [
    {
      id: 's10',
      title: 'Loki (Seasons 1 & 2)',
      releaseDate: 'Jun 9, 2021',
      chronologicalOrder: 29,
      releaseOrder: 29,
      isEssential: true,
      summary: 'Loki works with the TVA to master time slipping, ultimately becoming God of Stories holding Yggdrasil together.',
      imdbRating: 8.2,
      mediaType: 'series',
      rowIndex: 4,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Establishes TVA, timeline branches, temporalloom collapse, and multiversal tree format!',
      runtime: '12 Episodes',
      phase: 4,
    },
    {
      id: 's9',
      title: 'Hawkeye',
      releaseDate: 'Nov 24, 2021',
      chronologicalOrder: 32,
      releaseOrder: 32,
      isEssential: false,
      summary: 'Clint Barton mentors Kate Bishop in New York City while confronting Ronin ghosts.',
      imdbRating: 7.5,
      mediaType: 'series',
      rowIndex: 4,
      posterUrl: 'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?w=400&q=80',
      multiverseNote: 'Introduces Kate Bishop and brings Kingpin back to MCU canon.',
      runtime: '6 Episodes',
      phase: 4,
    },
  ],
  // Row 6 (L -> R)
  [
    {
      id: 's11',
      title: 'Moon Knight',
      releaseDate: 'Mar 30, 2022',
      chronologicalOrder: 35,
      releaseOrder: 35,
      isEssential: false,
      summary: 'Steven Grant and Marc Spector navigate DID while serving as avatar to Egyptian moon god Khonshu.',
      imdbRating: 7.3,
      mediaType: 'series',
      rowIndex: 5,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'Explores Egyptian pantheon dimension and supernatural realm.',
      runtime: '6 Episodes',
      phase: 4,
    },
    {
      id: 's12',
      title: 'Ms. Marvel',
      releaseDate: 'Jun 8, 2022',
      chronologicalOrder: 36,
      releaseOrder: 36,
      isEssential: false,
      summary: 'Kamala Khan discovers cosmic bangles that unlock light powers and Clandestine history.',
      imdbRating: 6.3,
      mediaType: 'series',
      rowIndex: 5,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Bangles connect to Noor Dimension and Quantum Realm tech leading to The Marvels.',
      runtime: '6 Episodes',
      phase: 4,
    },
  ],
  // Row 7 (R -> L)
  [
    {
      id: 's14',
      title: 'She-Hulk: Attorney at Law',
      releaseDate: 'Aug 18, 2022',
      chronologicalOrder: 38,
      releaseOrder: 38,
      isEssential: false,
      summary: 'Jennifer Walters balances high-stakes superhuman legal cases with fourth-wall breaking powers.',
      imdbRating: 5.3,
      mediaType: 'series',
      rowIndex: 6,
      posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&q=80',
      multiverseNote: 'Breaks fourth wall to alter plot construct directly.',
      runtime: '9 Episodes',
      phase: 4,
    },
    {
      id: 's13',
      title: 'Echo',
      releaseDate: 'Jan 9, 2024',
      chronologicalOrder: 45,
      releaseOrder: 45,
      isEssential: false,
      summary: 'Maya Lopez faces Kingpin while discovering her Choctaw ancestral superpower heritage.',
      imdbRating: 6.0,
      mediaType: 'series',
      rowIndex: 6,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Strengthens Kingpin mayor storyline in street-level NYC.',
      runtime: '5 Episodes',
      phase: 5,
    },
  ],
  // Row 8 (L -> R)
  [
    {
      id: 's15',
      title: 'Agatha All Along',
      releaseDate: 'Sep 18, 2024',
      chronologicalOrder: 49,
      releaseOrder: 49,
      isEssential: false,
      summary: 'Agatha Harkness walks the Witches’ Road to reclaim her lost magic with Billy Maximoff.',
      imdbRating: 7.2,
      mediaType: 'series',
      rowIndex: 7,
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=80',
      multiverseNote: 'Introduces Wiccan (Billy Maximoff) and cosmic mystical ley-lines.',
      runtime: '9 Episodes',
      phase: 5,
    },
    {
      id: 's16',
      title: 'Daredevil: Born Again',
      releaseDate: 'Mar 4, 2025',
      chronologicalOrder: 52,
      releaseOrder: 52,
      isEssential: false,
      summary: 'Matt Murdock and Wilson Fisk clash as Fisk ascends to Mayor of NYC.',
      imdbRating: 8.5,
      mediaType: 'series',
      rowIndex: 7,
      posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80',
      multiverseNote: 'Core street-level anchor before Doom incursions threaten Earth-616.',
      runtime: '9 Episodes',
      phase: 5,
    },
  ],
  // Row 9 (R -> L)
  [
    {
      id: 's18',
      title: 'Ironheart',
      releaseDate: 'Jun 24, 2025',
      chronologicalOrder: 54,
      releaseOrder: 54,
      isEssential: false,
      summary: 'Riri Williams fuses MIT tech armor engineering with mystical forces.',
      imdbRating: 7.0,
      mediaType: 'series',
      rowIndex: 8,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'Tech vs Magic conflict bridging Wakandan vibranium and Mephisto realm lore.',
      runtime: '6 Episodes',
      phase: 5,
    },
    {
      id: 's17',
      title: 'Wonder Man',
      releaseDate: 'Dec 2025',
      chronologicalOrder: 55,
      releaseOrder: 55,
      isEssential: false,
      summary: 'Hollywood actor Simon Williams gains ionic energy powers in a satirical superhero tale.',
      imdbRating: 7.2,
      mediaType: 'series',
      rowIndex: 8,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'Ionic energy spectrum user who can withstand multiversal radiation.',
      runtime: '10 Episodes',
      phase: 6,
    },
  ],
  // Row 10 (L -> R)
  [
    {
      id: 's19',
      title: 'Daredevil: Born Again (S2)',
      releaseDate: 'Mar 2026',
      chronologicalOrder: 57,
      releaseOrder: 57,
      isEssential: false,
      summary: 'NYC outlaw heroes unite against totalitarian anti-vigilante law.',
      imdbRating: 8.6,
      mediaType: 'series',
      rowIndex: 9,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Pre-crisis defense coalition.',
      runtime: '9 Episodes',
      phase: 6,
    },
    {
      id: 's20',
      title: 'Punisher: One Last Kill',
      releaseDate: 'May 2026',
      chronologicalOrder: 58,
      releaseOrder: 58,
      isEssential: false,
      summary: 'Frank Castle’s high-velocity tactical stand before global multiversal breakdown.',
      imdbRating: 8.1,
      mediaType: 'series',
      rowIndex: 9,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Final street-level chapter.',
      runtime: '6 Episodes',
      phase: 6,
    },
  ],
  // Row 11 (Centered) -> Convergence
  [
    {
      id: 's21',
      title: 'VisionQuest',
      releaseDate: 'Oct 2026',
      chronologicalOrder: 60,
      releaseOrder: 60,
      isEssential: false,
      summary: 'White Vision searches for his soul and memory across temporal dimensions.',
      imdbRating: 8.0,
      mediaType: 'series',
      rowIndex: 10,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'DIRECT CONVERGENCE NODE: Synthezoid temporal calculus connects directly into Avengers: Doomsday!',
      runtime: '6 Episodes',
      phase: 6,
    },
  ],
];

export const MOVIE_ROAD_ROWS: MCUItem[][] = [
  // Row 1 (L -> R)
  [
    {
      id: 'm1',
      title: 'Iron Man',
      releaseDate: 'May 2, 2008',
      chronologicalOrder: 2,
      releaseOrder: 1,
      isEssential: false,
      summary: 'Tony Stark builds the Mark I armor to escape captivity and launches the MCU.',
      imdbRating: 7.9,
      mediaType: 'movie',
      rowIndex: 0,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'Origin of Earth-616 hero technology.',
      runtime: '2h 6m',
      phase: 1,
    },
    {
      id: 'm2',
      title: 'The Incredible Hulk',
      releaseDate: 'Jun 13, 2008',
      chronologicalOrder: 3,
      releaseOrder: 2,
      isEssential: false,
      summary: 'Bruce Banner seeks a cure for gamma radiation while hunted by General Ross.',
      imdbRating: 6.6,
      mediaType: 'movie',
      rowIndex: 0,
      posterUrl: 'https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=400&q=80',
      multiverseNote: 'Gamma mutation baseline.',
      runtime: '1h 52m',
      phase: 1,
    },
    {
      id: 'm3',
      title: 'Iron Man 2',
      releaseDate: 'May 7, 2010',
      chronologicalOrder: 4,
      releaseOrder: 3,
      isEssential: false,
      summary: 'Tony Stark confronts palladium poisoning, Ivan Vanko, and introducing Black Widow.',
      imdbRating: 6.9,
      mediaType: 'movie',
      rowIndex: 0,
      posterUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&q=80',
      multiverseNote: 'Stark Expo tech foundation.',
      runtime: '2h 4m',
      phase: 1,
    },
  ],
  // Row 2 (R -> L)
  [
    {
      id: 'm6',
      title: 'The Avengers',
      releaseDate: 'May 4, 2012',
      chronologicalOrder: 6,
      releaseOrder: 6,
      isEssential: false,
      summary: 'Earth’s Mightiest Heroes assemble for the first time to stop Loki and the Chitauri.',
      imdbRating: 8.0,
      mediaType: 'movie',
      rowIndex: 1,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Original 2012 NYC timeline point used later for Endgame time heist.',
      runtime: '2h 23m',
      phase: 1,
    },
    {
      id: 'm5',
      title: 'Captain America: TFA',
      releaseDate: 'Jul 22, 2011',
      chronologicalOrder: 1,
      releaseOrder: 5,
      isEssential: false,
      summary: 'Steve Rogers takes super soldier serum and fights Red Skull during WWII.',
      imdbRating: 6.9,
      mediaType: 'movie',
      rowIndex: 1,
      posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&q=80',
      multiverseNote: 'Tesseract Space Stone discovery on Earth.',
      runtime: '2h 4m',
      phase: 1,
    },
    {
      id: 'm4',
      title: 'Thor',
      releaseDate: 'May 6, 2011',
      chronologicalOrder: 5,
      releaseOrder: 4,
      isEssential: false,
      summary: 'God of Thunder is banished to Earth by Odin to learn humility.',
      imdbRating: 7.0,
      mediaType: 'movie',
      rowIndex: 1,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'Introduces Nine Realms and Bifrost dimensional travel.',
      runtime: '1h 55m',
      phase: 1,
    },
  ],
  // Row 3 (L -> R)
  [
    {
      id: 'm7',
      title: 'Iron Man 3',
      releaseDate: 'May 3, 2013',
      chronologicalOrder: 7,
      releaseOrder: 7,
      isEssential: false,
      summary: 'Tony Stark struggles with PTSD while facing Aldrich Killian and Extremis.',
      imdbRating: 7.1,
      mediaType: 'movie',
      rowIndex: 2,
      posterUrl: 'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?w=400&q=80',
      multiverseNote: 'Stark armor iteration progress.',
      runtime: '2h 10m',
      phase: 2,
    },
    {
      id: 'm8',
      title: 'Thor: The Dark World',
      releaseDate: 'Nov 8, 2013',
      chronologicalOrder: 8,
      releaseOrder: 8,
      isEssential: false,
      summary: 'Thor teams with Loki to stop Malekith from using the Aether (Reality Stone).',
      imdbRating: 6.8,
      mediaType: 'movie',
      rowIndex: 2,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'Convergence of Nine Realms & Reality Stone lore.',
      runtime: '1h 52m',
      phase: 2,
    },
    {
      id: 'm9',
      title: 'Captain America: Winter Soldier',
      releaseDate: 'Apr 4, 2014',
      chronologicalOrder: 9,
      releaseOrder: 9,
      isEssential: false,
      summary: 'Steve Rogers and Natasha Romanoff uncover Hydra infiltration inside S.H.I.E.L.D.',
      imdbRating: 7.8,
      mediaType: 'movie',
      rowIndex: 2,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Bucky Barnes survival and global geopolitical shift.',
      runtime: '2h 16m',
      phase: 2,
    },
  ],
  // Row 4 (R -> L)
  [
    {
      id: 'm12',
      title: 'Ant-Man',
      releaseDate: 'Jul 17, 2015',
      chronologicalOrder: 12,
      releaseOrder: 12,
      isEssential: false,
      summary: 'Scott Lang learns Pym Particles shrinking technology and enters Quantum Realm.',
      imdbRating: 7.3,
      mediaType: 'movie',
      rowIndex: 3,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'CRITICAL TECH: First entry into Quantum Realm time-space nexus.',
      runtime: '1h 57m',
      phase: 2,
    },
    {
      id: 'm11',
      title: 'Avengers: Age of Ultron',
      releaseDate: 'May 1, 2015',
      chronologicalOrder: 10,
      releaseOrder: 11,
      isEssential: false,
      summary: 'Tony Stark creates AI Ultron who attempts human extinction; Vision is born.',
      imdbRating: 7.3,
      mediaType: 'movie',
      rowIndex: 3,
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=80',
      multiverseNote: 'Mind Stone creation of Vision and Wanda Maximoff origin.',
      runtime: '2h 21m',
      phase: 2,
    },
    {
      id: 'm10',
      title: 'Guardians of the Galaxy',
      releaseDate: 'Aug 1, 2014',
      chronologicalOrder: 10,
      releaseOrder: 10,
      isEssential: false,
      summary: 'Peter Quill, Gamora, Drax, Rocket, and Groot team up to secure the Power Stone.',
      imdbRating: 8.0,
      mediaType: 'movie',
      rowIndex: 3,
      posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80',
      multiverseNote: 'Opens cosmic MCU scale and celestial lore.',
      runtime: '2h 1m',
      phase: 2,
    },
  ],
  // Row 5 (L -> R)
  [
    {
      id: 'm13',
      title: 'Captain America: Civil War',
      releaseDate: 'May 6, 2016',
      chronologicalOrder: 14,
      releaseOrder: 13,
      isEssential: false,
      summary: 'Sokovia Accords splinter Avengers into Team Cap and Team Iron Man.',
      imdbRating: 7.8,
      mediaType: 'movie',
      rowIndex: 4,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Introduces Spider-Man and Black Panther to Earth-616 line-up.',
      runtime: '2h 27m',
      phase: 3,
    },
    {
      id: 'm14',
      title: 'Doctor Strange',
      releaseDate: 'Nov 4, 2016',
      chronologicalOrder: 15,
      releaseOrder: 14,
      isEssential: false,
      summary: 'Stephen Strange learns Mystic Arts at Kamar-Taj and wields the Eye of Agamotto.',
      imdbRating: 7.5,
      mediaType: 'movie',
      rowIndex: 4,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'Time Stone loops and Astral Plane dimensional mechanics.',
      runtime: '1h 55m',
      phase: 3,
    },
    {
      id: 'm15',
      title: 'Guardians of the Galaxy Vol. 2',
      releaseDate: 'May 5, 2017',
      chronologicalOrder: 18,
      releaseOrder: 15,
      isEssential: false,
      summary: 'Peter Quill meets his father Ego the Living Planet, a cosmic Celestial.',
      imdbRating: 7.6,
      mediaType: 'movie',
      rowIndex: 4,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'Celestial god-like energy manifestations.',
      runtime: '2h 16m',
      phase: 3,
    },
  ],
  // Row 6 (R -> L)
  [
    {
      id: 'm18',
      title: 'Spider-Man: Homecoming',
      releaseDate: 'Jul 7, 2017',
      chronologicalOrder: 21,
      releaseOrder: 18,
      isEssential: false,
      summary: 'Peter Parker balances high school life with fighting Vulture.',
      imdbRating: 7.4,
      mediaType: 'movie',
      rowIndex: 5,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'Establishes Tom Holland Spider-Man baseline.',
      runtime: '2h 13m',
      phase: 3,
    },
    {
      id: 'm17',
      title: 'Thor: Ragnarok',
      releaseDate: 'Nov 3, 2017',
      chronologicalOrder: 22,
      releaseOrder: 17,
      isEssential: false,
      summary: 'Thor loses Mjolnir, battles Hulk on Sakaar, and witnesses destruction of Asgard.',
      imdbRating: 7.9,
      mediaType: 'movie',
      rowIndex: 5,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Destruction of Asgard leading directly into Thanos assault.',
      runtime: '2h 10m',
      phase: 3,
    },
    {
      id: 'm16',
      title: 'Black Panther',
      releaseDate: 'Feb 16, 2018',
      chronologicalOrder: 23,
      releaseOrder: 16,
      isEssential: false,
      summary: 'T’Challa returns to Wakanda to claim the throne and face Killmonger.',
      imdbRating: 7.3,
      mediaType: 'movie',
      rowIndex: 5,
      posterUrl: 'https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=400&q=80',
      multiverseNote: 'Wakandan Vibranium defense shield system.',
      runtime: '2h 14m',
      phase: 3,
    },
  ],
  // Row 7 (L -> R)
  [
    {
      id: 'm19',
      title: 'Avengers: Infinity War',
      releaseDate: 'Apr 27, 2018',
      chronologicalOrder: 24,
      releaseOrder: 19,
      isEssential: false,
      summary: 'Thanos collects all six Infinity Stones and snaps away half of all life in the universe.',
      imdbRating: 8.4,
      mediaType: 'movie',
      rowIndex: 6,
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=80',
      multiverseNote: 'The Snap catastrophe that tore temporal stability across the cosmos.',
      runtime: '2h 29m',
      phase: 3,
    },
    {
      id: 'm20',
      title: 'Ant-Man and the Wasp',
      releaseDate: 'Jul 6, 2018',
      chronologicalOrder: 25,
      releaseOrder: 20,
      isEssential: false,
      summary: 'Scott Lang and Hope van Dyne rescue Janet van Dyne from the Quantum Realm.',
      imdbRating: 7.0,
      mediaType: 'movie',
      rowIndex: 6,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'Scott trapped in Quantum Realm during the Snap - key to time travel.',
      runtime: '1h 58m',
      phase: 3,
    },
    {
      id: 'm21',
      title: 'Captain Marvel',
      releaseDate: 'Mar 8, 2019',
      chronologicalOrder: 26,
      releaseOrder: 21,
      isEssential: false,
      summary: 'Carol Danvers unlocks lightspeed binary powers during 1990s Kree-Skrull war.',
      imdbRating: 6.8,
      mediaType: 'movie',
      rowIndex: 6,
      posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80',
      multiverseNote: 'Tesseract Space Stone power absorption.',
      runtime: '2h 4m',
      phase: 3,
    },
  ],
  // Row 8 (R -> L)
  [
    {
      id: 'm24',
      title: 'Avengers: Endgame',
      releaseDate: 'Apr 26, 2019',
      chronologicalOrder: 27,
      releaseOrder: 24,
      isEssential: true,
      summary: 'The surviving Avengers pull off a Time Heist through the Quantum Realm to undo Thanos’ snap.',
      imdbRating: 8.4,
      mediaType: 'movie',
      rowIndex: 7,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Created the branched timelines and temporal variants leading directly to Multiverse Saga!',
      runtime: '3h 1m',
      phase: 3,
    },
    {
      id: 'm23',
      title: 'Spider-Man: Far From Home',
      releaseDate: 'Jul 2, 2019',
      chronologicalOrder: 28,
      releaseOrder: 23,
      isEssential: false,
      summary: 'Peter Parker travels to Europe and battles Mysterio’s elemental holograms.',
      imdbRating: 7.4,
      mediaType: 'movie',
      rowIndex: 7,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'Mysterio falsified multiverse lies, pre-conditioning public for real multiverse.',
      runtime: '2h 9m',
      phase: 3,
    },
    {
      id: 'm22',
      title: 'Black Widow',
      releaseDate: 'Jul 9, 2021',
      chronologicalOrder: 29,
      releaseOrder: 22,
      isEssential: false,
      summary: 'Natasha Romanoff confronts her dark Red Room history alongside Yelena Belova.',
      imdbRating: 6.7,
      mediaType: 'movie',
      rowIndex: 7,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'Introduces Yelena Belova and Red Guardian for Thunderbolts team-up.',
      runtime: '2h 14m',
      phase: 4,
    },
  ],
  // Row 9 (L -> R)
  [
    {
      id: 'm25',
      title: 'Shang-Chi & Legend of 10 Rings',
      releaseDate: 'Sep 3, 2021',
      chronologicalOrder: 30,
      releaseOrder: 25,
      isEssential: false,
      summary: 'Shang-Chi claims the thousand-year-old Ten Rings and defends Ta Lo.',
      imdbRating: 7.4,
      mediaType: 'movie',
      rowIndex: 8,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'Ten Rings beacon sending a signal across the multiverse.',
      runtime: '2h 12m',
      phase: 4,
    },
    {
      id: 'm26',
      title: 'Eternals',
      releaseDate: 'Nov 5, 2021',
      chronologicalOrder: 31,
      releaseOrder: 26,
      isEssential: false,
      summary: 'Ancient immortals emerge after 7,000 years to save Earth from Celestial Tiamut birth.',
      imdbRating: 6.3,
      mediaType: 'movie',
      rowIndex: 8,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'Celestial Tiamut frozen Adamantium island in Earth ocean.',
      runtime: '2h 36m',
      phase: 4,
    },
    {
      id: 'm27',
      title: 'Spider-Man: No Way Home',
      releaseDate: 'Dec 17, 2021',
      chronologicalOrder: 33,
      releaseOrder: 27,
      isEssential: true,
      summary: 'Peter Parker asks Doctor Strange to erase public memory, fracturing space-time and pulling villains/heroes from Tobey & Andrew universes.',
      imdbRating: 8.2,
      mediaType: 'movie',
      rowIndex: 8,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: First major live-action multiversal rupture bringing past Spider-Man dimensions together!',
      runtime: '2h 28m',
      phase: 4,
    },
  ],
  // Row 10 (R -> L)
  [
    {
      id: 'm30',
      title: 'Doctor Strange in Multiverse of Madness',
      releaseDate: 'May 6, 2022',
      chronologicalOrder: 34,
      releaseOrder: 30,
      isEssential: true,
      summary: 'Doctor Strange protects America Chavez from Wanda Maximoff, traveling across alternate earths (Earth-838 Illuminati).',
      imdbRating: 6.9,
      mediaType: 'movie',
      rowIndex: 9,
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Defines multiversal INCURSIONS (colliding universes) which form the core plot of Avengers: Doomsday!',
      runtime: '2h 6m',
      phase: 4,
    },
    {
      id: 'm29',
      title: 'Thor: Love and Thunder',
      releaseDate: 'Jul 8, 2022',
      chronologicalOrder: 37,
      releaseOrder: 29,
      isEssential: false,
      summary: 'Thor teams with Mighty Thor (Jane Foster) to defeat Gorr the God Butcher.',
      imdbRating: 6.2,
      mediaType: 'movie',
      rowIndex: 9,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'Eternity wish realm access.',
      runtime: '1h 59m',
      phase: 4,
    },
    {
      id: 'm28',
      title: 'Black Panther: Wakanda Forever',
      releaseDate: 'Nov 11, 2022',
      chronologicalOrder: 39,
      releaseOrder: 28,
      isEssential: false,
      summary: 'Wakanda mourns T’Challa while Shuri becomes Black Panther to negotiate peace with Namor’s Talokan.',
      imdbRating: 6.7,
      mediaType: 'movie',
      rowIndex: 9,
      posterUrl: 'https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=400&q=80',
      multiverseNote: 'Vibranium geopolitical tension setting up global war.',
      runtime: '2h 41m',
      phase: 4,
    },
  ],
  // Row 11 (L -> R)
  [
    {
      id: 'm31',
      title: 'Ant-Man & Wasp: Quantumania',
      releaseDate: 'Feb 17, 2023',
      chronologicalOrder: 40,
      releaseOrder: 31,
      isEssential: true,
      summary: 'Ant-Man and family are pulled into subatomic Quantum Realm city state, battling temporal empire technology.',
      imdbRating: 6.0,
      mediaType: 'movie',
      rowIndex: 10,
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Unveils the quantum realm temporal scale and multiversal citadel mechanics!',
      runtime: '2h 5m',
      phase: 5,
    },
    {
      id: 'm32',
      title: 'Guardians of the Galaxy Vol. 3',
      releaseDate: 'May 5, 2023',
      chronologicalOrder: 41,
      releaseOrder: 32,
      isEssential: false,
      summary: 'The Guardians embark on a mission to save Rocket from High Evolutionary.',
      imdbRating: 7.9,
      mediaType: 'movie',
      rowIndex: 10,
      posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80',
      multiverseNote: 'Genetic engineering & Counter-Earth planet scale.',
      runtime: '2h 30m',
      phase: 5,
    },
    {
      id: 'm33',
      title: 'The Marvels',
      releaseDate: 'Nov 10, 2023',
      chronologicalOrder: 42,
      releaseOrder: 33,
      isEssential: false,
      summary: 'Carol Danvers, Kamala Khan, and Monica Rambeau swap places when using powers, sealing a dimensional tear to X-Men universe.',
      imdbRating: 5.5,
      mediaType: 'movie',
      rowIndex: 10,
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
      multiverseNote: 'Rifts between Earth-616 and X-Men reality (Earth-838/10005).',
      runtime: '1h 45m',
      phase: 5,
    },
  ],
  // Row 12 (R -> L)
  [
    {
      id: 'm36',
      title: 'Deadpool & Wolverine',
      releaseDate: 'Jul 26, 2024',
      chronologicalOrder: 46,
      releaseOrder: 36,
      isEssential: true,
      summary: 'Deadpool is recruited by the TVA to save his timeline from annihilation, uniting with a variant Wolverine from the Void.',
      imdbRating: 7.8,
      mediaType: 'movie',
      rowIndex: 11,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Establishes ANCHOR BEINGS, the Void, mutant universe integration, and TVA multiversal defense!',
      runtime: '2h 8m',
      phase: 5,
    },
    {
      id: 'm35',
      title: 'Captain America: Brave New World',
      releaseDate: 'Feb 14, 2025',
      chronologicalOrder: 50,
      releaseOrder: 35,
      isEssential: true,
      summary: 'Sam Wilson meets President Thaddeus Red Hulk Ross as international conflict erupts over Celestial Tiamut’s Adamantium ore.',
      imdbRating: 7.7,
      mediaType: 'movie',
      rowIndex: 11,
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Sets up Earth’s new political world order and Adamantium military power struggle before Doomsday!',
      runtime: '2h 10m',
      phase: 5,
    },
    {
      id: 'm34',
      title: 'Thunderbolts*',
      releaseDate: 'May 2, 2025',
      chronologicalOrder: 51,
      releaseOrder: 34,
      isEssential: true,
      summary: 'Yelena Belova, Bucky Barnes, U.S. Agent, Red Guardian, Ghost, and Taskmaster are trapped by Valentina and encounter Sentry.',
      imdbRating: 7.9,
      mediaType: 'movie',
      rowIndex: 11,
      posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Anti-hero team dynamics and Bob Reynolds (Sentry) void-level cosmic threat leading to global crisis!',
      runtime: '2h 15m',
      phase: 5,
    },
  ],
  // Row 13 (L -> R) -> Convergence
  [
    {
      id: 'm37',
      title: 'The Fantastic Four: First Steps',
      releaseDate: 'Jul 25, 2025',
      chronologicalOrder: 53,
      releaseOrder: 37,
      isEssential: true,
      summary: 'Set in a retro-futuristic 1960s alternate universe Earth, Reed Richards, Sue Storm, Johnny Storm, and Ben Grimm face Galactus and Silver Surfer.',
      imdbRating: 8.5,
      mediaType: 'movie',
      rowIndex: 12,
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
      multiverseNote: 'ABSOLUTE ESSENTIAL: Direct introduction of DOCTOR VICTOR VON DOOM and Fantastic 4 multiversal migration into Earth-616!',
      runtime: '2h 20m',
      phase: 6,
    },
    {
      id: 'm38',
      title: 'Spider-Man: Brand New Day',
      releaseDate: 'Jul 30, 2026',
      chronologicalOrder: 59,
      releaseOrder: 38,
      isEssential: false,
      summary: 'Peter Parker navigates life completely erased from human memory while dark forces threaten New York.',
      imdbRating: 8.3,
      mediaType: 'movie',
      rowIndex: 12,
      posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&q=80',
      multiverseNote: 'DIRECT CONVERGENCE NODE: Final movie milestone right before the Incursion event in Avengers: Doomsday!',
      runtime: '2h 25m',
      phase: 6,
    },
  ],
];

export const DOOMSDAY_CONVERGENCE_ITEM: MCUItem = {
  id: 'doomsday_final',
  title: 'Avengers: Doomsday',
  releaseDate: 'Dec 18, 2026',
  chronologicalOrder: 100,
  releaseOrder: 100,
  isEssential: true,
  summary: 'Doctor Victor Von Doom unleashes multiversal incursions, forcing Earth’s heroes and multiversal variants to unite for survival.',
  imdbRating: 9.9,
  mediaType: 'movie',
  rowIndex: 99,
  posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
  multiverseNote: 'THE FINAL CONVERGENCE: Robert Downey Jr. strikes as Doctor Doom in the ultimate multiversal clash!',
  runtime: 'TBD',
  phase: 6,
};
